In [ ]:
import pandas as pd

# 전국데이터
df_national = pd.read_csv("경찰청_연도별_실종아동등_가출인_접수_및_해제현황_20251231.csv", encoding="cp949")
df_national.head()

,연도,18세_미만_아동_접수,18세_미만_아동_해제,18세_미만_아동_미해제,지적자폐성정신장애인_접수,지적자폐성정신장애인_해제,지적자폐성정신장애인_미해제,치매환자_접수,치매환자_해제,치매환자_미해제,가출인(실종성인)_접수,가출인(실종성인)_해제,가출인(실종성인)_미해제
0,2021,21379,21257,1,7166,7168,4,12577,12562,9,66259,66536,261
1,2022,26416,26357,8,8344,8337,5,14527,14525,8,74936,75755,250
2,2023,25628,25516,6,8440,8434,9,14677,14654,11,74847,74827,317
3,2024,25692,25602,3,8430,8404,7,15502,15487,10,71854,71703,471
4,2025,29563,29448,67,8420,8406,31,16586,16570,15,70814,70591,765

In [ ]:
# 인천데이터
df_incheon = pd.read_csv("경찰청_인천광역시경찰청_아동_실종신고_현황_20251231.csv", encoding="cp949")
df_incheon.head()

     구분   중부  미추홀   남동   부평   서부   계양  강화   연수   삼산   논현
0  2025  172  291  176  270  357  174   7  320  212  274
1  2024  146  207  159  160  393  143  15  273  291  187
2  2023  138  235  153  430  518  128  18  253  340  144
3  2022  114  218  169  331  388  115  10  194  399  170
4  2021   89  242  137  278  289   74   6  192  199  118

In [3]:
# 전국: 18세 미만 아동 접수만
df_national = df_national[["연도", "18세_미만_아동_접수"]]

# 인천: 연도별 합계 계산 + 2021년 이후만 필터링
df_incheon["합계"] = df_incheon.iloc[:, 1:].sum(axis=1)
df_incheon_recent = df_incheon[df_incheon["구분"] >= 2021]
df_incheon_recent[["구분", "합계"]]

     구분    합계
0  2025  2253
1  2024  1974
2  2023  2357
3  2022  2108
4  2021  1624

In [4]:
df_national

     연도  18세_미만_아동_접수
0  2021         21379
1  2022         26416
2  2023         25628
3  2024         25692
4  2025         29563

In [5]:
df_incheon_recent[["구분", "합계"]]

     구분    합계
0  2025  2253
1  2024  1974
2  2023  2357
3  2022  2108
4  2021  1624